export const PATIENT_RELATIONSHIPS = [
  { label: 'Husband', value: 'Husband' },
  { label: 'Wife', value: 'Wife' },
  { label: 'Father', value: 'Father' },
  { label: 'Mother', value: 'Mother' },
  { label: 'Son', value: 'Son' },
  { label: 'Daughter', value: 'Daughter' },
  { label: 'Brother', value: 'Brother' },
  { label: 'Sister', value: 'Sister' },
  { label: 'Grandfather', value: 'Grandfather' },
  { label: 'Grandmother', value: 'Grandmother' },
  { label: 'Spouse', value: 'Spouse' },
  { label: 'Father & Mother', value: 'Father & Mother' },
  { label: 'Cousin Brother', value: 'Cousin Brother' },
  { label: 'Cousin Sister', value: 'Cousin Sister' },
  { label: 'Paternal Uncle', value: 'Paternal Uncle' },
  { label: 'Paternal Aunt', value: 'Paternal Aunt' },
  { label: 'Maternal Uncle', value: 'Maternal Uncle' },
  { label: 'Maternal Aunt', value: 'Maternal Aunt' },
  { label: 'Paternal Grandfather', value: 'Paternal Grandfather' },
  { label: 'Paternal Grandmother', value: 'Paternal Grandmother' },
  { label: 'Maternal Grandfather', value: 'Maternal Grandfather' },
  { label: 'Maternal Grandmother', value: 'Maternal Grandmother' },
  { label: 'Great grandfather', value: 'Great grandfather' },
  { label: 'Great grandmother', value: 'Great grandmother' },
  { label: 'Niece', value: 'Niece' },
  { label: 'Nephew', value: 'Nephew' }
] as const
