import { type CountryCode } from '@/types/common'

export const countryCodes: CountryCode[] = [
  { label: '🇦🇫 Afghanistan (+93)', value: '93', isoCode: 'AF' },
  { label: '🇦🇱 Albania (+355)', value: '355', isoCode: 'AL' },
  { label: '🇩🇿 Algeria (+213)', value: '213', isoCode: 'DZ' },
  { label: '🇦🇩 Andorra (+376)', value: '376', isoCode: 'AD' },
  { label: '🇦🇴 Angola (+244)', value: '244', isoCode: 'AO' },
  { label: '🇦🇷 Argentina (+54)', value: '54', isoCode: 'AR' },
  { label: '🇦🇲 Armenia (+374)', value: '374', isoCode: 'AM' },
  { label: '🇦🇺 Australia (+61)', value: '61', isoCode: 'AU' },
  { label: '🇦🇹 Austria (+43)', value: '43', isoCode: 'AT' },
  { label: '🇦🇿 Azerbaijan (+994)', value: '994', isoCode: 'AZ' },
  { label: '🇧🇭 Bahrain (+973)', value: '973', isoCode: 'BH' },
  { label: '🇧🇩 Bangladesh (+880)', value: '880', isoCode: 'BD' },
  { label: '🇧🇾 Belarus (+375)', value: '375', isoCode: 'BY' },
  { label: '🇧🇪 Belgium (+32)', value: '32', isoCode: 'BE' },
  { label: '🇧🇿 Belize (+501)', value: '501', isoCode: 'BZ' },
  { label: '🇧🇯 Benin (+229)', value: '229', isoCode: 'BJ' },
  { label: '🇧🇹 Bhutan (+975)', value: '975', isoCode: 'BT' },
  { label: '🇧🇴 Bolivia (+591)', value: '591', isoCode: 'BO' },
  { label: '🇧🇦 Bosnia and Herzegovina (+387)', value: '387', isoCode: 'BA' },
  { label: '🇧🇼 Botswana (+267)', value: '267', isoCode: 'BW' },
  { label: '🇧🇷 Brazil (+55)', value: '55', isoCode: 'BR' },
  { label: '🇧🇳 Brunei (+673)', value: '673', isoCode: 'BN' },
  { label: '🇧🇬 Bulgaria (+359)', value: '359', isoCode: 'BG' },
  { label: '🇧🇫 Burkina Faso (+226)', value: '226', isoCode: 'BF' },
  { label: '🇧🇮 Burundi (+257)', value: '257', isoCode: 'BI' },
  { label: '🇰🇭 Cambodia (+855)', value: '855', isoCode: 'KH' },
  { label: '🇨🇲 Cameroon (+237)', value: '237', isoCode: 'CM' },
  { label: '🇨🇦 Canada (+1)', value: '1', isoCode: 'CA' },
  { label: '🇨🇻 Cape Verde (+238)', value: '238', isoCode: 'CV' },
  { label: '🇨🇫 Central African Republic (+236)', value: '236', isoCode: 'CF' },
  { label: '🇹🇩 Chad (+235)', value: '235', isoCode: 'TD' },
  { label: '🇨🇱 Chile (+56)', value: '56', isoCode: 'CL' },
  { label: '🇨🇳 China (+86)', value: '86', isoCode: 'CN' },
  { label: '🇨🇴 Colombia (+57)', value: '57', isoCode: 'CO' },
  { label: '🇰🇲 Comoros (+269)', value: '269', isoCode: 'KM' },
  { label: '🇨🇩 Congo (DRC) (+243)', value: '243', isoCode: 'CD' },
  { label: '🇨🇬 Congo (Republic) (+242)', value: '242', isoCode: 'CG' },
  { label: '🇨🇷 Costa Rica (+506)', value: '506', isoCode: 'CR' },
  { label: '🇭🇷 Croatia (+385)', value: '385', isoCode: 'HR' },
  { label: '🇨🇺 Cuba (+53)', value: '53', isoCode: 'CU' },
  { label: '🇨🇾 Cyprus (+357)', value: '357', isoCode: 'CY' },
  { label: '🇨🇿 Czech Republic (+420)', value: '420', isoCode: 'CZ' },
  { label: '🇩🇰 Denmark (+45)', value: '45', isoCode: 'DK' },
  { label: '🇩🇯 Djibouti (+253)', value: '253', isoCode: 'DJ' },
  { label: '🇩🇴 Dominican Republic (+1-809)', value: '1-809', isoCode: 'DO' },
  { label: '🇹🇱 East Timor (+670)', value: '670', isoCode: 'TL' },
  { label: '🇪🇨 Ecuador (+593)', value: '593', isoCode: 'EC' },
  { label: '🇪🇬 Egypt (+20)', value: '20', isoCode: 'EG' },
  { label: '🇸🇻 El Salvador (+503)', value: '503', isoCode: 'SV' },
  { label: '🇬🇶 Equatorial Guinea (+240)', value: '240', isoCode: 'GQ' },
  { label: '🇪🇷 Eritrea (+291)', value: '291', isoCode: 'ER' },
  { label: '🇪🇪 Estonia (+372)', value: '372', isoCode: 'EE' },
  { label: '🇸🇿 Eswatini (+268)', value: '268', isoCode: 'SZ' },
  { label: '🇪🇹 Ethiopia (+251)', value: '251', isoCode: 'ET' },
  { label: '🇫🇯 Fiji (+679)', value: '679', isoCode: 'FJ' },
  { label: '🇫🇮 Finland (+358)', value: '358', isoCode: 'FI' },
  { label: '🇫🇷 France (+33)', value: '33', isoCode: 'FR' },
  { label: '🇬🇦 Gabon (+241)', value: '241', isoCode: 'GA' },
  { label: '🇬🇲 Gambia (+220)', value: '220', isoCode: 'GM' },
  { label: '🇬🇪 Georgia (+995)', value: '995', isoCode: 'GE' },
  { label: '🇩🇪 Germany (+49)', value: '49', isoCode: 'DE' },
  { label: '🇬🇭 Ghana (+233)', value: '233', isoCode: 'GH' },
  { label: '🇬🇷 Greece (+30)', value: '30', isoCode: 'GR' },
  { label: '🇬🇹 Guatemala (+502)', value: '502', isoCode: 'GT' },
  { label: '🇬🇳 Guinea (+224)', value: '224', isoCode: 'GN' },
  { label: '🇬🇼 Guinea-Bissau (+245)', value: '245', isoCode: 'GW' },
  { label: '🇬🇾 Guyana (+592)', value: '592', isoCode: 'GY' },
  { label: '🇭🇹 Haiti (+509)', value: '509', isoCode: 'HT' },
  { label: '🇭🇳 Honduras (+504)', value: '504', isoCode: 'HN' },
  { label: '🇭🇺 Hungary (+36)', value: '36', isoCode: 'HU' },
  { label: '🇮🇸 Iceland (+354)', value: '354', isoCode: 'IS' },
  { label: '🇮🇳 India (+91)', value: '91', isoCode: 'IN' },
  { label: '🇮🇩 Indonesia (+62)', value: '62', isoCode: 'ID' },
  { label: '🇮🇷 Iran (+98)', value: '98', isoCode: 'IR' },
  { label: '🇮🇶 Iraq (+964)', value: '964', isoCode: 'IQ' },
  { label: '🇮🇪 Ireland (+353)', value: '353', isoCode: 'IE' },
  { label: '🇮🇱 Israel (+972)', value: '972', isoCode: 'IL' },
  { label: '🇮🇹 Italy (+39)', value: '39', isoCode: 'IT' },
  { label: '🇨🇮 Ivory Coast (+225)', value: '225', isoCode: 'CI' },
  { label: '🇯🇲 Jamaica (+1-876)', value: '1-876', isoCode: 'JM' },
  { label: '🇯🇵 Japan (+81)', value: '81', isoCode: 'JP' },
  { label: '🇯🇴 Jordan (+962)', value: '962', isoCode: 'JO' },
  { label: '🇰🇿 Kazakhstan (+7)', value: '7', isoCode: 'KZ' },
  { label: '🇰🇪 Kenya (+254)', value: '254', isoCode: 'KE' },
  { label: '🇰🇮 Kiribati (+686)', value: '686', isoCode: 'KI' },
  { label: '🇽🇰 Kosovo (+383)', value: '383', isoCode: 'XK' },
  { label: '🇰🇼 Kuwait (+965)', value: '965', isoCode: 'KW' },
  { label: '🇰🇬 Kyrgyzstan (+996)', value: '996', isoCode: 'KG' },
  { label: '🇱🇦 Laos (+856)', value: '856', isoCode: 'LA' },
  { label: '🇱🇻 Latvia (+371)', value: '371', isoCode: 'LV' },
  { label: '🇱🇧 Lebanon (+961)', value: '961', isoCode: 'LB' },
  { label: '🇱🇸 Lesotho (+266)', value: '266', isoCode: 'LS' },
  { label: '🇱🇷 Liberia (+231)', value: '231', isoCode: 'LR' },
  { label: '🇱🇾 Libya (+218)', value: '218', isoCode: 'LY' },
  { label: '🇱🇮 Liechtenstein (+423)', value: '423', isoCode: 'LI' },
  { label: '🇱🇹 Lithuania (+370)', value: '370', isoCode: 'LT' },
  { label: '🇱🇺 Luxembourg (+352)', value: '352', isoCode: 'LU' },
  { label: '🇲🇬 Madagascar (+261)', value: '261', isoCode: 'MG' },
  { label: '🇲🇼 Malawi (+265)', value: '265', isoCode: 'MW' },
  { label: '🇲🇾 Malaysia (+60)', value: '60', isoCode: 'MY' },
  { label: '🇲🇻 Maldives (+960)', value: '960', isoCode: 'MV' },
  { label: '🇲🇱 Mali (+223)', value: '223', isoCode: 'ML' },
  { label: '🇲🇹 Malta (+356)', value: '356', isoCode: 'MT' },
  { label: '🇲🇷 Mauritania (+222)', value: '222', isoCode: 'MR' },
  { label: '🇲🇺 Mauritius (+230)', value: '230', isoCode: 'MU' },
  { label: '🇲🇽 Mexico (+52)', value: '52', isoCode: 'MX' },
  { label: '🇫🇲 Micronesia (+691)', value: '691', isoCode: 'FM' },
  { label: '🇲🇩 Moldova (+373)', value: '373', isoCode: 'MD' },
  { label: '🇲🇨 Monaco (+377)', value: '377', isoCode: 'MC' },
  { label: '🇲🇳 Mongolia (+976)', value: '976', isoCode: 'MN' },
  { label: '🇲🇪 Montenegro (+382)', value: '382', isoCode: 'ME' },
  { label: '🇲🇦 Morocco (+212)', value: '212', isoCode: 'MA' },
  { label: '🇲🇿 Mozambique (+258)', value: '258', isoCode: 'MZ' },
  { label: '🇲🇲 Myanmar (+95)', value: '95', isoCode: 'MM' },
  { label: '🇳🇦 Namibia (+264)', value: '264', isoCode: 'NA' },
  { label: '🇳🇷 Nauru (+674)', value: '674', isoCode: 'NR' },
  { label: '🇳🇵 Nepal (+977)', value: '977', isoCode: 'NP' },
  { label: '🇳🇱 Netherlands (+31)', value: '31', isoCode: 'NL' },
  { label: '🇳🇿 New Zealand (+64)', value: '64', isoCode: 'NZ' },
  { label: '🇳🇮 Nicaragua (+505)', value: '505', isoCode: 'NI' },
  { label: '🇳🇪 Niger (+227)', value: '227', isoCode: 'NE' },
  { label: '🇳🇬 Nigeria (+234)', value: '234', isoCode: 'NG' },
  { label: '🇰🇵 North Korea (+850)', value: '850', isoCode: 'KP' },
  { label: '🇲🇰 North Macedonia (+389)', value: '389', isoCode: 'MK' },
  { label: '🇳🇴 Norway (+47)', value: '47', isoCode: 'NO' },
  { label: '🇴🇲 Oman (+968)', value: '968', isoCode: 'OM' },
  { label: '🇵🇰 Pakistan (+92)', value: '92', isoCode: 'PK' },
  { label: '🇵🇼 Palau (+680)', value: '680', isoCode: 'PW' },
  { label: '🇵🇸 Palestine (+970)', value: '970', isoCode: 'PS' },
  { label: '🇵🇦 Panama (+507)', value: '507', isoCode: 'PA' },
  { label: '🇵🇬 Papua New Guinea (+675)', value: '675', isoCode: 'PG' },
  { label: '🇵🇾 Paraguay (+595)', value: '595', isoCode: 'PY' },
  { label: '🇵🇪 Peru (+51)', value: '51', isoCode: 'PE' },
  { label: '🇵🇭 Philippines (+63)', value: '63', isoCode: 'PH' },
  { label: '🇵🇱 Poland (+48)', value: '48', isoCode: 'PL' },
  { label: '🇵🇹 Portugal (+351)', value: '351', isoCode: 'PT' },
  { label: '🇶🇦 Qatar (+974)', value: '974', isoCode: 'QA' },
  { label: '🇷🇴 Romania (+40)', value: '40', isoCode: 'RO' },
  { label: '🇷🇺 Russia (+7)', value: '7', isoCode: 'RU' },
  { label: '🇷🇼 Rwanda (+250)', value: '250', isoCode: 'RW' },
  { label: '🇸🇲 San Marino (+378)', value: '378', isoCode: 'SM' },
  { label: '🇸🇹 São Tomé and Príncipe (+239)', value: '239', isoCode: 'ST' },
  { label: '🇸🇦 Saudi Arabia (+966)', value: '966', isoCode: 'SA' },
  { label: '🇸🇳 Senegal (+221)', value: '221', isoCode: 'SN' },
  { label: '🇷🇸 Serbia (+381)', value: '381', isoCode: 'RS' },
  { label: '🇸🇨 Seychelles (+248)', value: '248', isoCode: 'SC' },
  { label: '🇸🇱 Sierra Leone (+232)', value: '232', isoCode: 'SL' },
  { label: '🇸🇬 Singapore (+65)', value: '65', isoCode: 'SG' },
  { label: '🇸🇰 Slovakia (+421)', value: '421', isoCode: 'SK' },
  { label: '🇸🇮 Slovenia (+386)', value: '386', isoCode: 'SI' },
  { label: '🇸🇧 Solomon Islands (+677)', value: '677', isoCode: 'SB' },
  { label: '🇸🇴 Somalia (+252)', value: '252', isoCode: 'SO' },
  { label: '🇿🇦 South Africa (+27)', value: '27', isoCode: 'ZA' },
  { label: '🇰🇷 South Korea (+82)', value: '82', isoCode: 'KR' },
  { label: '🇸🇸 South Sudan (+211)', value: '211', isoCode: 'SS' },
  { label: '🇪🇸 Spain (+34)', value: '34', isoCode: 'ES' },
  { label: '🇱🇰 Sri Lanka (+94)', value: '94', isoCode: 'LK' },
  { label: '🇸🇩 Sudan (+249)', value: '249', isoCode: 'SD' },
  { label: '🇸🇷 Suriname (+597)', value: '597', isoCode: 'SR' },
  { label: '🇸🇪 Sweden (+46)', value: '46', isoCode: 'SE' },
  { label: '🇨🇭 Switzerland (+41)', value: '41', isoCode: 'CH' },
  { label: '🇸🇾 Syria (+963)', value: '963', isoCode: 'SY' },
  { label: '🇹🇼 Taiwan (+886)', value: '886', isoCode: 'TW' },
  { label: '🇹🇯 Tajikistan (+992)', value: '992', isoCode: 'TJ' },
  { label: '🇹🇿 Tanzania (+255)', value: '255', isoCode: 'TZ' },
  { label: '🇹🇭 Thailand (+66)', value: '66', isoCode: 'TH' },
  { label: '🇹🇬 Togo (+228)', value: '228', isoCode: 'TG' },
  { label: '🇹🇴 Tonga (+676)', value: '676', isoCode: 'TO' },
  { label: '🇹🇳 Tunisia (+216)', value: '216', isoCode: 'TN' },
  { label: '🇹🇷 Turkey (+90)', value: '90', isoCode: 'TR' },
  { label: '🇹🇲 Turkmenistan (+993)', value: '993', isoCode: 'TM' },
  { label: '🇹🇻 Tuvalu (+688)', value: '688', isoCode: 'TV' },
  { label: '🇺🇬 Uganda (+256)', value: '256', isoCode: 'UG' },
  { label: '🇺🇦 Ukraine (+380)', value: '380', isoCode: 'UA' },
  { label: '🇦🇪 United Arab Emirates (+971)', value: '971', isoCode: 'AE' },
  { label: '🇬🇧 United Kingdom (+44)', value: '44', isoCode: 'GB' },
  { label: '🇺🇸 United States (+1)', value: '1', isoCode: 'US' },
  { label: '🇺🇾 Uruguay (+598)', value: '598', isoCode: 'UY' },
  { label: '🇺🇿 Uzbekistan (+998)', value: '998', isoCode: 'UZ' },
  { label: '🇻🇺 Vanuatu (+678)', value: '678', isoCode: 'VU' },
  { label: '🇻🇦 Vatican City (+39)', value: '39', isoCode: 'VA' },
  { label: '🇻🇪 Venezuela (+58)', value: '58', isoCode: 'VE' },
  { label: '🇻🇳 Vietnam (+84)', value: '84', isoCode: 'VN' },
  { label: '🇾🇪 Yemen (+967)', value: '967', isoCode: 'YE' },
  { label: '🇿🇲 Zambia (+260)', value: '260', isoCode: 'ZM' },
  { label: '🇿🇼 Zimbabwe (+263)', value: '263', isoCode: 'ZW' }
]
